# 测试Opaque
# 必须是base64 加密后的
# 测试场景
#创建一个secret，然后再创建一个pod，这个pod以volume的形式挂载这个secret

apiVersion: v1
kind: Secret
metadata:
  name: test-secret-opaque-0511
  namespace: test
type: Opaque
data:
  username: YWRtaW4=
  password: c2YxMjM0NTY=
---
# 创建一个pod以volume的形势挂载上面的配置
apiVersion: v1
kind: Pod
metadata:
  name: test-secret-opaque-env-0511
  namespace: test
spec:
  containers:
    - name: test-secret-opaque-env
      image: hub.haoshuliang.com/library/nginx:v1.0.1
      command: ["env"]
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: test-secret-opaque-0511
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-secret-opaque-0511
              key: password
  restartPolicy: Never

#[root@k8s-master yaml_files]# kubectl log test-secret-opaque-env-0511 -n test
#log is DEPRECATED and will be removed in a future version. Use logs instead.
#PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
#HOSTNAME=test-secret-opaque-env-0511
#USERNAME=admin
#PASSWORD=sf123456
#KUBERNETES_PORT=tcp://10.1.0.1:443
#KUBERNETES_PORT_443_TCP=tcp://10.1.0.1:443
#KUBERNETES_PORT_443_TCP_PROTO=tcp
#KUBERNETES_PORT_443_TCP_PORT=443
#KUBERNETES_PORT_443_TCP_ADDR=10.1.0.1
#KUBERNETES_SERVICE_HOST=10.1.0.1
#KUBERNETES_SERVICE_PORT=443
#KUBERNETES_SERVICE_PORT_HTTPS=443
#NGINX_VERSION=1.19.10
#NJS_VERSION=0.5.3
#PKG_RELEASE=1~buster
#HOME=/root

