# 测试Opaque
# 必须是base64 加密后的
# 测试场景
#创建一个secret，然后再创建一个pod，这个pod以volume的形式挂载这个secret

apiVersion: v1
kind: Secret
metadata:
  name: test-secret-opaque-0511
  namespace: test
type: Opaque
data:
  username: YWRtaW4=
  password: c2YxMjM0NTY=
---
# 创建一个pod以volume的形势挂载上面的配置
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-get-opaque-secret-0511
  namespace: test
  labels:
    name: test-pod-get-opaque-secret
spec:
  containers:
    - image: hub.haoshuliang.com/library/nginx:v1.0.1
      name: db
      volumeMounts:
        - name: secrets
          mountPath: "/etc/secret"
          readOnly: true
  volumes:
    - name: secrets
      secret:
        secretName: test-secret-opaque-0511

#[root@k8s-master yaml_files]# kubectl -n test exec -it test-pod-get-opaque-secret-0511 -- more /etc/secret/username
#admin
#[root@k8s-master yaml_files]# kubectl -n test exec -it test-pod-get-opaque-secret-0511 -- more /etc/secret/password
#sf123456
