# 测试创建一个docker-registry,下面是命令：
# kubectl create secret docker-registry my-hub   --docker-server=hub.haoshuliang.com   --docker-username=admin   --docker-password=Harbor12345   --docker-email=shulianghao@163.com -n test

# kubectl create secret docker-registry my-hub \
#  --docker-server=hub.haoshuliang.com \
#  --docker-username=admin \
#  --docker-password=Harbor12345 \
#  --docker-email=shulianghao@163.com

# 创建一个简单的pod去读取
apiVersion: v1
kind: Pod
metadata:
  name: foo
  namespace: test
spec:
  containers:
    - name: foo
      image: hub.haoshuliang.com/test/nginx:v1.0.1
  imagePullSecrets:
    - name: my-hub