version: '3'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql57/data:/var/lib/mysql
      - /data/mysql57/logs:/var/log/mysql
      - /data/mysql57/cnf/:/etc/mysql/
    command: [
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci',
            '--max_connections=3000'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    restart: always 
    networks:
      - mysql
networks:
  mysql:
