version: '3.8'

services:
  rancher:
    image: rancher/rancher:latest
    container_name: rancher
    ports:
      - "7080:80"
      - "7443:443"
    volumes:
      - "/data/rancher:/var/lib/rancher"
      - "/data/rancher_auditlog:/var/log/auditlog"
    restart: always
    privileged: true

