version: '3.7'

services:
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - "9081:8080"
    networks:
      - prom
    restart: always
networks:
  prom:
    driver: bridge
