version: '3'

services:
  dns_bind:
    image: sameersbn/bind:latest
    ports:
      - "53:53/udp"
      - "10000:10000/tcp"
    environment:
      WEBMIN_ENABLED: "false"
    volumes:
      - /data/dns_bind:/data
    restart: always
    privileged: true

