version: '3.1'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 7080:80
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - TZ=Asia/Shanghai
